#!/usr/bin/env bash

nc -z -G 2 arx.veracitydoc.com 22 2&>/dev/null >/dev/null
if [[ $? -ne 0 ]]; then
  echo "arx took too long to establish a connection. You probably need to run sneak"
  exit 1
fi

if [[ -z "$(lsof -Pi :5436 -sTCP:LISTEN -t)" ]]; then
  ARGS="$ARGS -L 5436:singularity.db.us-east-1.vix:5432"
  ARGS="$ARGS -L 5437:logging.db.us-east-1.vix:5432"
  ARGS="$ARGS -L 5438:entity.db.us-east-1.vix:5432"
fi

echo -ne "\033]Ph440000\033\\"
ssh $ARGS arx
echo -ne "\033]Ph000000\033\\"
