#!/usr/bin/env bash

nc -z -G 2 arx.veracityops.com 22 2&>/dev/null >/dev/null
if [[ $? -ne 0 ]]; then
  echo "arx-ops took too long to establish a connection. You probably need to run sneak"
  exit 1
fi

if [[ -z "$(lsof -Pi :5439 -sTCP:LISTEN -t)" ]]; then
  ARGS="$ARGS -L 5439:ops.cby3nvbeul0v.us-east-1.rds.amazonaws.com:5432"
fi

echo -ne "\033]Ph440000\033\\"
ssh $ARGS arx-ops
echo -ne "\033]Ph000000\033\\"
