#!/usr/bin/env bash

SCRIPT='
set term png size 800,250;
set margins -1,1,1,1;
set nokey;
set border lc rgbcolor "#888888";
set monochrome;
plot "-" using ($0+1):1 with lines;
'
OUTPUT="$(gnuplot -e "$SCRIPT" | base64)"

printf "\033]1337;File=inline=1:%s\a\n" "$OUTPUT"
