#!/usr/bin/env bash

REMOTE_URL="$(git remote get-url origin 2>&1)"
[[ $? -ne 0 ]] && {
  echo "$REMOTE_URL"
  exit 1
}

[[ "$REMOTE_URL" =~ ^git@github.com:(.*).git ]] || {
  echo "Not a github repo"
  echo "origin: ${REMOTE_URL}"
  exit 1
}

PROJECT="${BASH_REMATCH[1]}"
open "https://github.com/$PROJECT"
