#!/usr/bin/env bash

[[ "$1" == "--stdin" ]] && {
  USE_STDIN=1
  shift;
}

IN_FILE="$HOME/spike/interview_problem/base/solutions/$1.in"
OUT_FILE="$HOME/spike/interview_problem/base/solutions/$1.out"
shift;

if [[ -n "$USE_STDIN" ]]; then
  RESULT="$("$@" < $IN_FILE)"
else
  RESULT="$("$@" $IN_FILE)"
fi
colordiff -y <(echo "$RESULT") $OUT_FILE
