#!/usr/bin/env bash
RED="$(tput setaf 1)"
YELLOW="$(tput setaf 3)"
GREEN="$(tput setaf 2)"
RESET="$(tput sgr0)"

[[ "$1" == "--stdin" ]] && {
  USE_STDIN=1
  shift;
}


for IN_FILE in $(ls ~/spike/interview_problem/base/solutions/*.in); do
  OUT_FILE=${IN_FILE%.in}.out
  echo -n "$(basename "${IN_FILE%.in}"): "
  if [[ -n "$USE_STDIN" ]]; then
    RESULT="$("$@" < ${IN_FILE})"
  else
    RESULT="$("$@" ${IN_FILE})"
  fi
  if [[ 0 -eq $? ]]; then
    if cmp -s <(echo "$RESULT") $OUT_FILE;  then
      echo "${GREEN}ok${RESET}"
    else
      echo "${YELLOW}mismatch${RESET}"
    fi
  else
    echo "${RED}error${RESET}"
    echo "$RESULT"
    echo ""
  fi
done
