#!/bin/zsh

cd "$OS_REPO_HOME"
doFind(){
  find "website/app" -type f -name '*.js' -o -name '*.jsx' \
   | grep -v -e 'tests' -e '\.raw\.' \
   | sort \
   | xargs wc -l
}

output="$(doFind)"
echo "$output"

