#!/usr/bin/env bash

URL_PATH="$1"
shift

if [[ -z "$URL_PATH" ]]; then
  echo "Usage: trello URL_PATH [ARG_NAME==ARG_VALUE]..."
  exit 1
fi

exec http \
 --body \
 --pretty none \
 --stream \
 "https://api.trello.com/1/$URL_PATH" \
 "key==$(cat ~/.vix/trello_key)" \
 "token==$(cat ~/.vix/trello_token)" \
 "$@"
