#!/usr/bin/env bash

while true; do
  /System/Library/PrivateFrameworks/Apple80211.framework/Versions/Current/Resources/airport -I \
    | awk '
    /agrCtlRSSI/ {rssi = $2};
    /agrCtlNoise/ {noise = $2};
    /lastTxRate/ {tx = $2};
    END { print "rssi=" rssi "  noise=" noise "  tx=" tx }
  '
  sleep 0.5
done
